import { CalendarEvent, Calendar } from "./types"

export const WEEK_DAYS = ["일", "월", "화", "수", "목", "금", "토"]
export const WEEK_DATES = [3, 4, 5, 6, 7, 8, 9]
export const TIME_SLOTS = Array.from({ length: 9 }, (_, i) => i + 8) // 8 AM to 4 PM

export const SAMPLE_EVENTS: CalendarEvent[] = [
  // 월요일 (SUN - index 0)
  {
    id: 1,
    title: "팀 미팅",
    startTime: "09:00",
    endTime: "10:00",
    color: "bg-blue-500",
    day: 1,
    description: "주간 팀 동기화 회의",
    location: "회의실 A",
    attendees: ["김철수", "이영희", "박민수"],
    organizer: "정지훈",
  },
  {
    id: 2,
    title: "클라이언트 통화",
    startTime: "10:00",
    endTime: "11:00",
    color: "bg-yellow-500",
    day: 1,
    description: "신규 프로젝트 요구사항 논의",
    location: "온라인",
    attendees: ["ABC 회사"],
    organizer: "영업팀",
  },
  {
    id: 3,
    title: "점심 미팅",
    startTime: "12:30",
    endTime: "13:30",
    color: "bg-green-500",
    day: 1,
    description: "프로젝트 일정 논의",
    location: "1층 카페",
    attendees: ["김서연"],
    organizer: "나",
  },
  {
    id: 4,
    title: "제품 기획",
    startTime: "14:00",
    endTime: "15:30",
    color: "bg-pink-500",
    day: 1,
    description: "Q2 제품 로드맵 검토",
    location: "회의실 B",
    attendees: ["기획팀", "개발팀"],
    organizer: "제품 매니저",
  },
  
  // 화요일 (MON - index 1)
  {
    id: 5,
    title: "스탠드업 미팅",
    startTime: "09:30",
    endTime: "10:00",
    color: "bg-blue-500",
    day: 2,
    description: "일일 진행상황 공유",
    location: "개발팀 자리",
    attendees: ["개발팀 전원"],
    organizer: "스크럼 마스터",
  },
  {
    id: 6,
    title: "예산 검토",
    startTime: "13:30",
    endTime: "14:00",
    color: "bg-yellow-500",
    day: 2,
    description: "Q2 예산 집행 현황",
    location: "재무팀 회의실",
    attendees: ["CFO", "재무팀"],
    organizer: "재무 이사",
  },
  
  // 수요일 (TUE - index 2 - 현재 날짜 5일)
  {
    id: 7,
    title: "팀 훈련",
    startTime: "09:30",
    endTime: "11:30",
    color: "bg-green-500",
    day: 3,
    description: "신규 도구 교육",
    location: "교육실",
    attendees: ["전 직원"],
    organizer: "HR팀",
  },
  {
    id: 8,
    title: "제품 데모",
    startTime: "11:00",
    endTime: "12:00",
    color: "bg-pink-500",
    day: 3,
    description: "신기능 시연",
    location: "대회의실",
    attendees: ["임원진", "주요 고객"],
    organizer: "제품팀",
  },
  {
    id: 9,
    title: "클라이언트 프레젠테이션",
    startTime: "11:00",
    endTime: "12:30",
    color: "bg-orange-500",
    day: 3,
    description: "프로젝트 진행 현황 보고",
    location: "회의실 C",
    attendees: ["XYZ 회사", "프로젝트팀"],
    organizer: "PM",
  },
  
  // 목요일 (WED - index 3)
  {
    id: 10,
    title: "브레인스토밍",
    startTime: "13:00",
    endTime: "14:30",
    color: "bg-purple-500",
    day: 4,
    description: "신규 기능 아이디어 회의",
    location: "창의실",
    attendees: ["개발팀", "디자인팀"],
    organizer: "CTO",
  },
  
  // 금요일 (THU - index 4)
  {
    id: 11,
    title: "마케팅 미팅",
    startTime: "13:00",
    endTime: "14:00",
    color: "bg-green-500",
    day: 5,
    description: "캠페인 전략 논의",
    location: "마케팅팀 회의실",
    attendees: ["마케팅팀", "대행사"],
    organizer: "마케팅 이사",
  },
  {
    id: 12,
    title: "디자인 리뷰",
    startTime: "14:30",
    endTime: "15:45",
    color: "bg-purple-500",
    day: 5,
    description: "UI/UX 개선사항 검토",
    location: "디자인실",
    attendees: ["디자인팀", "개발팀"],
    organizer: "디자인 리드",
  },
  
  // 토요일 (FRI - index 5)
  {
    id: 13,
    title: "투자자 미팅",
    startTime: "10:30",
    endTime: "12:00",
    color: "bg-red-500",
    day: 6,
    description: "분기 실적 보고",
    location: "임원 회의실",
    attendees: ["CEO", "CFO", "투자자"],
    organizer: "CEO",
  },
  
  // 일요일 (SAT - index 6)
  {
    id: 14,
    title: "코드 리뷰",
    startTime: "15:00",
    endTime: "16:00",
    color: "bg-indigo-500",
    day: 7,
    description: "주간 코드 품질 검토",
    location: "온라인",
    attendees: ["시니어 개발자들"],
    organizer: "Tech Lead",
  },
]

export const MY_CALENDARS: Calendar[] = [
  { id: "1", name: "My Calendar", color: "bg-blue-500", isActive: true },
  { id: "2", name: "Work", color: "bg-green-500", isActive: true },
  { id: "3", name: "Personal", color: "bg-purple-500", isActive: true },
  { id: "4", name: "Family", color: "bg-orange-500", isActive: true },
]